spring:
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/task_database
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234

  jpa:
    show-sql: true
    open-in-view: false
